### ISSUE TITLE
TimeSpan format

### ISSUE THREAD

**Issue by igitur** [andersnm/ExcelNumberFormat#10]
I assume TimeSpan format hasn't been completed. I'll try to submit some PR's later. 

But here are some things I've noticed.

1. Excel doesn't format timespans with milliseconds included, unless it's explicitly in the format, e.g. `h:mm:ss.000`.
2. `AM/PM` suffix doesn't work.

Unit test would be updated to:
```c#
        [TestMethod]
        public void TestTimeSpan()
        {
            Test(new TimeSpan(100, 0, 0), "[hh]:mm:ss", "100:00:00");
            Test(new TimeSpan(100, 0, 0), "[mm]:ss", "6000:00");
            Test(TimeSpan.FromDays(0.575916551), "h:mm:ss", "13:49:19");
            Test(TimeSpan.FromDays(0.575916551), "h:mm:ss AM/PM", "1:49:19 PM"); 
        }
```

**Comment by andersnm** [comment]
Thanks for pointing these out. I'm looking at improving the milliseconds currently.

Note that the last two Test()s are technically testing DateTime formatting. The format "h:mm:ss AM/PM" contains only datetime tokens (and no elapsed/absolute tokens [hh], [mm], [ss]), so the Formatter converts the value to a DateTime and formats internally using Formatter.FormatDate().

If the format contains one of the elapsed/absolute tokens [hh], [mm], [ss], the Formatter casts to a TimeSpan and formats internally using Formatter.FormatTimeSpan().

**Comment by igitur** [comment]
Oh, I wasn't aware of *elapsed* time formats. I'll go read up about it.
