### ISSUE TITLE
Date separator according to culture 

### ISSUE THREAD

**Issue by pmajIDC** [andersnm/ExcelNumberFormat#15]
Hi, I am using package to formatting date time and I find the problem with date separator in different culture. 
You can easy fixed it.  You can add condition, which replace '/' with date separator, in method FormatLiteral in class Formatter.  

For example: 
else if (token.Length == 1 && token[0] == '/' && culture != null) 
{
       literal = DateTime.MaxValue.ToString("/d", culture)[0].ToString();
}

**Comment by andersnm** [comment]
Hi and thanks for the report! Just released this as version 1.0.6!
