### ISSUE TITLE
Support t/tt tokens

### ISSUE THREAD

**Issue by asdobson** [andersnm/ExcelNumberFormat#28]
Libraries such as ClosedXML will pass in "t" or "tt" for predefined indexed formats rather than "a/p" or "am/pm".

Treat "t" token as "a/p", and "tt" as "am/pm"

**Comment by andersnm** [comment]
Hi,

As long as Excel does not support it, I don't think we should add it to this library:

![image](https://user-images.githubusercontent.com/16575282/83490484-642b9a80-a4b0-11ea-9011-36a2f3314b4e.png)

I assume t/tt are the tokens used for AM/PM in the .NET format strings, and ClosedXML incorrectly allowed these at some earlier time before adopting ExcelNumberFormat. If ClosedXML has code to insert these tokens, it's a bug on their end.
