### ISSUE TITLE
Porting ExcelNumberFormat to Javascript?

### ISSUE THREAD

**Issue by clement911** [andersnm/ExcelNumberFormat#29]
Hi @andersnm 

First of all thank you for this wonderful library!
It seems very promising  and the code seems very clean.
We are very likely going to take a dependency on it to format numbers and dates in some generated reports in our .net core app.

Ok, so this is not really an issue with the library but I was wondering if you have considered porting this library to javascript?
We would definitely use it to format numbers and dates in the browser.

We have found only a single decent existing javascript library, https://github.com/SheetJS/ssf

I'm sure you're aware of it since I've seen ssf referenced in the source a few times.
But unfortunately, there are quite a few open issues with it, and more importantly it doesn't support custom locales (Unlike ExcelNumberFormat).  So, we can't customize the decimal and thousands separators, and date elements (day names, month names, etc...). It always uses the US culture.

**Comment by andersnm** [comment]
Hi @clement911,

Thank you - always happy to hear people finding this little niche library useful :-) I don't have any concrete plans to port it to JS.

**Comment by clement911** [comment]
Fair enough. I had to ask :)
Thanks for making this project anyway.

**Comment by clement911** [comment]
Hi @andersnm 

Would you be willing to create an open-source Typescript/NPM port for it if I paid you for it?

We're running into some issues with [ssf](https://github.com/SheetJS/ssf) . We can't customize the thousand separator, use bigints, some formats just don't work, etc...

**Comment by andersnm** [comment]
@clement911 Alas no.

**Comment by clement911** [comment]
@andersnm , understood. I appreciate the fast and clear response 😉.
I will likely do the port myself at some point, using mostly the code from ExcelNumberFormat as a starting point to translate to Typescript.
I'll keep you posted when/if I ever get to that..

**Comment by clement911** [comment]
FYI, this was implemeted recently.
https://github.com/Wish-Org/sheet-number-formatter
