### ISSUE TITLE
Trouble at installation

### ISSUE THREAD

**Issue by ChuckRau** [andersnm/ExcelNumberFormat#40]
I'm installing into a brand new Windows Form Application .NET Framework 4.7.2 in Visual Studio 2022 community edition.  The install fails with the following error:

![InstallIssue](https://github.com/andersnm/ExcelNumberFormat/assets/143551538/340d1e40-bc58-4a0d-be9f-61a562e795b9)

I also tried this in VS 2019 and got the same error.

Any thoughts?

**Comment by andersnm** [comment]
The error message says the nuget package file is corrupt. Try delete it.

**Comment by ChuckRau** [comment]
I went to the .nuget\packages directory and deleted the ExcelNumberFormat directory.

I then ran: NuGet\Install-Package ExcelNumberFormat -Version 1.1.0

I got the same error.  BTW, its Windows 10.



Package Manager Console Host Version 6.7.0.127

Type 'get-help NuGet' to see all available NuGet commands.

PM> NuGet\Install-Package ExcelNumberFormat -Version 1.1.0


Attempting to gather dependency information for package 'ExcelNumberFormat.1.1.0' with respect to project 'TABBankDaily', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 308 ms
Attempting to resolve dependencies for package 'ExcelNumberFormat.1.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ExcelNumberFormat.1.1.0'
Resolved actions to install package 'ExcelNumberFormat.1.1.0'
Retrieving package 'ExcelNumberFormat 1.1.0' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/excelnumberformat/1.1.0/excelnumberformat.1.1.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/excelnumberformat/1.1.0/excelnumberformat.1.1.0.nupkg 14ms
Installed ExcelNumberFormat 1.1.0 from https://api.nuget.org/v3/index.json with content hash R3BVHPs9O+RkExbZYTGT0+9HLbi8ZrNij1Yziyw6znd3J7P3uoIR07uwTLGOogtz1p6+0sna66eBoXu7tBiVQA==.
Adding package 'ExcelNumberFormat.1.1.0' to folder 'G:\My Drive\EBG Work Documents\Software Projects\TABBankDaily\packages'
Install failed. Rolling back...
Package 'ExcelNumberFormat.1.1.0' does not exist in project 'TABBankDaily'
Removing package 'ExcelNumberFormat.1.1.0' from folder 'G:\My Drive\EBG Work Documents\Software Projects\TABBankDaily\packages'
NuGet\Install-Package : The file is not a valid nupkg. File path: G:\My Drive\EBG Work Documents\Software Projects\TABBankDaily\packages\ExcelNumberFormat.1.1.0\ExcelNumberFormat.1.1.0.nupkg
  Central Directory corrupt.
  An attempt was made to move the file pointer before the beginning of the file.
At line:1 char:1
+ NuGet\Install-Package ExcelNumberFormat -Version 1.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:02.4041161
One or more packages could not be completely uninstalled: 'G:\My Drive\EBG Work Documents\Software Projects\TABBankDaily\packages\ExcelNumberFormat.1.1.0'. Restart Visual Studio to finish uninstall.
PM>

**Comment by andersnm** [comment]
The error message says the downloaded nupkg file is broken, but the file is fine here:
https://api.nuget.org/v3-flatcontainer/excelnumberformat/1.1.0/excelnumberformat.1.1.0.nupkg

`Central Directory corrupt.` indicates some sort of unzipping problem. Maybe you need a newer Nuget version? The package nupkg was created by VS, so it's got to be some broader issue rather than to do with this library. (if I were to investigate I'd have to install VS2022 to try repro, check if other packages have problems too, search for the error message on google etc)

**Comment by ChuckRau** [comment]
I've been searching Google many different ways to see if someone else ran into this but no dice.  This really is a strange one.  I have the library installed on a couple other projects from a while back without any issue.
